# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel
before_install:
  - curl http://r.research.att.com/libs/clang-4.0.0-darwin15.6-Release.tar.gz
  - sudo tar fvxz clang-4.0.0-darwin15.6-Release.tar.gz -C 
after_success:
  - Rscript -e 'covr::codecov()'
r_github_packages:
  - hadley/devtools